name: Release

on:
  release:
    types: [ published ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout master
      uses: actions/checkout@v4
      with:
        ref: master

    - name: Set up Git
      run: |
        git config user.name 'github-actions'
        git config user.email 'github-actions@github.com'

    - name: Get version from release tag
      id: get_version
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
    
    - name: Merge develop into master
      run: |
        git checkout master
        git merge develop --no-ff
        git push origin master

    - name: Bump version in package.json
      run: |
        npm version $RELEASE_VERSION

    - name: Push changes
      run: |
        git push origin master --follow-tags
