name: Release

on:
  release:
    types: [ published ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout master
      uses: actions/checkout@v4
      with:
        ref: master

    - name: Set up Git
      run: |
        git config user.name 'github-actions'
        git config user.email 'github-actions@github.com'
    
    - name: Merge develop into master
      run: |
        git checkout master
        git merge develop --no-ff
        git push origin master

    - name: Create Release Tag
      id: create_tag
      run: |
        NEW_TAG=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
        echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
        git tag $NEW_TAG
        git push origin $NEW_TAG
