name: Release

on:
  release:
    types: [ published ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout master
      uses: actions/checkout@v4
      with:
        ref: master

    - name: Set up Git
      run: |
        git config user.name 'github-actions'
        git config user.email 'github-actions@github.com'

    - name: Get version from release tag
      id: get_version
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Fetch branches
      run: |
        git fetch origin master develop

    - name: Merge develop into master
      run: |
        git merge develop --no-ff || git merge --abort

    - name: Bump version in package.json
      run: |
        npm version $RELEASE_VERSION
        git add package.json package-lock.json
        git commit -am "Bump version to $RELEASE_VERSION"

    - name: Push changes to master
      run: git push origin master --follow-tags

    - name: Merge master into develop
      run: |
        git checkout develop
        git merge master --no-ff

    - name: Push changes to develop
      run: |
        git push origin develop
