name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout master
      uses: actions/checkout@v4
      with:
        ref: master

    - name: Set up Git
      run: |
        git config user.name 'github-actions'
        git config user.email 'github-actions@github.com'

    - name: Get version from release tag
      id: get_version
      run: echo "RELEASE_VERSION=$(echo ${{ github.event.inputs.version }} | sed 's/^v//')" >> $GITHUB_ENV

    - name: Fetch branches
      run: |
        git fetch origin

    - name: Checkout and create local develop
      run: git checkout -b develop origin/develop

    - name: Merge develop into master
      run: |
        git checkout master
        git merge develop --no-ff || git merge --abort

    - name: Bump version in package.json
      run: |
        npm version $RELEASE_VERSION

    - name: Push changes to master
      run: git push origin master --follow-tags

    - name: Merge master into develop
      run: |
        git checkout develop
        git merge master --no-ff

    - name: Push changes to develop
      run: |
        git push origin develop
